[package]
name = "optic"
version = "0.1.0"
authors = ["Jan Verbeek <jan.verbeek@posteo.nl>"]
description = "Minimalist pedantic command line parser"
keywords = ["args", "arguments", "cli", "parser", "getopt"]
categories = ["command-line-interface"]
readme = "README.md"
edition = "2018"
