name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain add 1.40
      - run: cargo +1.40 test

  test-windows:
    name: Test (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain add 1.40
      - run: cargo +1.40 test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add x86_64-pc-windows-msvc wasm32-wasi wasm32-unknown-unknown

      - name: rustfmt
        run: cargo fmt -- --check

      - name: clippy (Linux)
        run: cargo clippy -- -D warnings

      - name: clippy (Windows)
        run: cargo clippy --target x86_64-pc-windows-msvc -- -D warnings

      - name: clippy (WASI)
        run: cargo clippy --target wasm32-wasi -- -D warnings

      - name: clippy (wasm32)
        run: cargo clippy --target wasm32-unknown-unknown -- -D warnings
