name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain add 1.31 1.39 stable nightly
      - run: cargo +1.31 test --lib  # MSRV (examples don't compile)
      - run: cargo +1.39 test        # First version where examples compile
      - run: cargo +stable test
      - run: cargo +nightly test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add x86_64-pc-windows-msvc wasm32-wasi wasm32-unknown-unknown

      - name: rustfmt
        run: cargo fmt -- --check

      - name: clippy (Linux)
        run: cargo clippy -- -D warnings

      - name: clippy (Windows)
        run: cargo clippy --target x86_64-pc-windows-msvc -- -D warnings

      - name: clippy (WASI)
        run: cargo clippy --target wasm32-wasi -- -D warnings

      - name: clippy (wasm32)
        run: cargo clippy --target wasm32-unknown-unknown -- -D warnings
