name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.40.0
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: clippy (Linux)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - run: rustup target add x86_64-pc-windows-msvc wasm32-wasi wasm32-unknown-unknown

      - name: clippy (Windows)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target x86_64-pc-windows-msvc -- -D warnings

      - name: clippy (WASI)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target wasm32-wasi -- -D warnings

      - name: clippy (wasm32)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target wasm32-unknown-unknown -- -D warnings
